version: "3.9"

services:
  chatapp:
    build: .
    container_name: chatapp
    ports:
      - "80:8000"
    environment:
      - APP_SECRET=ilovepisco220
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    working_dir: /code
