version: "3.9"

services:
  chatapp:
    build: .
    container_name: chatapp
    ports:
      - "80:8000"
    environment:
      - APP_SECRET=ilovepisco220
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./code:/code   # 掛載本機，修改即時生效
      - ./static:/static:ro
      - ./uploads:/uploads
